name: Java CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Проверяем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # Устанавливаем Java JDK
      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 17 # Указываем версию Java
          distribution: 'temurin' # Указываем дистрибутив Java

      # Проверяем, что Java установлена
      - name: Verify Java installation
        run: java -version
